// @generated by `cargo run -p xtask -- generate-api-types`. Do not edit.
//! Enrollment wire types, generated from `api/enrollment-v1alpha1.yaml`.
//!
//! Regenerate with `cargo run -p xtask -- generate-api-types`. The format
//! decisions live in `xtask/src/api_codegen.rs`.

#![allow(
    missing_docs,
    unused_qualifications,
    reason = "typify-generated wire types are not hand-maintained"
)]

/**What the provider serves. An advertisement grants nothing: a site
decides for itself whether to believe it and whether to route
there, so a false claim costs the believer one failed request.
*/
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default, Eq, PartialEq)]
pub struct Capabilities {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub inference: ::std::option::Option<CapabilitiesInference>,
}
///Inference the provider offers.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default, Eq, PartialEq)]
pub struct CapabilitiesInference {
    ///The models served.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub models: ::std::vec::Vec<ModelCapability>,
}
///Where peers reach this provider once it is a member.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct Egress {
    ///Host and port of the provider's gateway.
    pub address: ::std::string::String,
    ///Name peers present in SNI, when it differs from the address.
    #[serde(
        rename = "serverName",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub server_name: ::std::option::Option<::std::string::String>,
}
/**Where a request has got to. Nothing is trusted before `issued`.
*/
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum EnrollmentPhase {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "issued")]
    Issued,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "failed")]
    Failed,
}
impl ::std::fmt::Display for EnrollmentPhase {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Pending => f.write_str("pending"),
            Self::Issued => f.write_str("issued"),
            Self::Denied => f.write_str("denied"),
            Self::Failed => f.write_str("failed"),
        }
    }
}
impl ::std::str::FromStr for EnrollmentPhase {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "pending" => Ok(Self::Pending),
            "issued" => Ok(Self::Issued),
            "denied" => Ok(Self::Denied),
            "failed" => Ok(Self::Failed),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for EnrollmentPhase {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for EnrollmentPhase {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///A request and whatever has been decided about it.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct EnrollmentRequest {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub capabilities: ::std::option::Option<Capabilities>,
    /**The issued certificate, PEM encoded. Present once issued.
Public material.
*/
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub certificate: ::std::option::Option<::std::string::String>,
    ///When the request arrived.
    #[serde(rename = "createdAt")]
    pub created_at: ::std::string::String,
    ///When it was approved or denied.
    #[serde(
        rename = "decidedAt",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub decided_at: ::std::option::Option<::std::string::String>,
    /**Who decided. Recorded so a grid can answer why a provider is
trusted, which a hand-edited allow list cannot.
*/
    #[serde(
        rename = "decidedBy",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub decided_by: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub egress: ::std::option::Option<Egress>,
    ///The grid being joined.
    #[serde(rename = "gridNetworkRef")]
    pub grid_network_ref: ::std::string::String,
    pub phase: EnrollmentPhase,
    /**Lowercase hex SHA-256 of the request's public key. Names the
key rather than the certificate, so it survives reissue.
*/
    #[serde(
        rename = "publicKeySha256",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub public_key_sha256: ::std::option::Option<::std::string::String>,
    ///Why it was refused, when it was.
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub reason: ::std::option::Option<::std::string::String>,
    ///Identifier for polling and for deciding.
    #[serde(rename = "requestId")]
    pub request_id: ::uuid::Uuid,
    ///The name asked for.
    #[serde(rename = "siteName")]
    pub site_name: ::std::string::String,
    /**The name the grid assigned, carried as a URI SAN on the
certificate.
*/
    #[serde(rename = "spiffeId", skip_serializing_if = "::std::option::Option::is_none")]
    pub spiffe_id: ::std::option::Option<::std::string::String>,
}
///What a provider submits to ask for membership.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct EnrollmentRequestInput {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub capabilities: ::std::option::Option<Capabilities>,
    /**PKCS#10 certificate signing request, PEM encoded. The private
key stays with the requester and is never sent.
*/
    pub csr: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub egress: ::std::option::Option<Egress>,
    ///The grid being joined.
    #[serde(rename = "gridNetworkRef")]
    pub grid_network_ref: ::std::string::String,
    /**The name being asked for. The grid grants this name or
refuses; it does not grant a different one.
*/
    #[serde(rename = "siteName")]
    pub site_name: ::std::string::String,
}
///A failure, described so a caller can act on it.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct Error {
    ///Machine-readable code.
    pub error: ::std::string::String,
    ///What went wrong, and what would fix it.
    pub message: ::std::string::String,
}
///One model a provider serves, and how to call it.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct ModelCapability {
    ///Request and response shape the provider speaks.
    #[serde(rename = "apiFormat")]
    pub api_format: ::std::string::String,
    ///Model identifier as the provider knows it.
    pub name: ::std::string::String,
    ///Absolute request path for this model.
    pub path: ::std::string::String,
}
/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
