apiVersion: v1
kind: Service
metadata:
  name: grid-enrollment
  namespace: models-as-a-service
  labels:
    app.kubernetes.io/name: grid-enrollment
    app.kubernetes.io/part-of: grid
spec:
  selector:
    app.kubernetes.io/name: grid-enrollment
  ports:
    - name: http
      port: 8080
      targetPort: http
