apiVersion: grid.praxis-proxy.io/v1alpha1
kind: GridNetwork
metadata:
  name: glb-demo
  labels:
    grid.praxis-proxy.io/auto-discover-sites: "true"
spec:
  gridId: ""
  region: us-central
  zone: us-central-1a

  seeds:
    - "{{ captures.site-us-east.swim-lb-ip }}:7946"
    - "{{ captures.site-us-west.swim-lb-ip }}:7946"

  swim:
    probeInterval: "5s"
    suspicionTimeout: "10s"
    gossipNodes: 3

  tls:
    caSecretRef: null
    siteSecretRef: null
    swimKeyRef: null
